In [33]:
import pandas as pd
import numpy as np
import statsmodels.stats.api as sms

# sms.DescrStatsW(a).tconfint_mean()

In [7]:
data = pd.read_csv('water.txt', sep='\t')

In [11]:
low_bound = data['mortality'].mean() - 2 * data['mortality'].std(ddof=1)

In [35]:
np.round(sms.DescrStatsW(data['mortality']).tconfint_mean(0.05), 4)

array([1476.0833, 1572.2117])

In [17]:
data

location           town  mortality  hardness
0     South           Bath       1247       105
1     North     Birkenhead       1668        17
2     South     Birmingham       1466         5
3     North      Blackburn       1800        14
4     North      Blackpool       1609        18
..      ...            ...        ...       ...
56    South        Walsall       1527        60
57    South  West Bromwich       1627        53
58    South       West Ham       1486       122
59    South  Wolverhampton       1485        81
60    North           York       1378        71

[61 rows x 4 columns]

In [34]:
df = data[data['location'] == 'South']
np.round(sms.DescrStatsW(df['mortality']).tconfint_mean(0.05), 4)

array([1320.1517, 1433.4636])

In [36]:
df = data[data['location'] == 'North']
np.round(sms.DescrStatsW(df['mortality']).tconfint_mean(0.05), 4)

array([1586.5605, 1680.6395])

In [37]:
df = data[data['location'] == 'South']
np.round(sms.DescrStatsW(df['hardness']).tconfint_mean(0.05), 4)

array([53.4672, 86.0713])

In [38]:
df = data[data['location'] == 'North']
np.round(sms.DescrStatsW(df['hardness']).tconfint_mean(0.05), 4)

array([21.4225, 39.3775])

In [16]:
odds_placebo = (189./11034.)/(1-(189./11034.))
odds_aspirin = (104./11037.)/(1-(104./11037.))
round(odds_placebo - odds_aspirin, 4)

0.0079

In [26]:
round((float(iplc) / plc) - (float(iasp) / asp), 4)

0.0077

In [28]:
odds_placebo = 189./11034.
odds_aspirin = 104./11037.
odds_placebo - odds_aspirin

0.0077060239760047815

In [ ]:
1.8320539419087143

In [19]:
def kek(total, cases):
    return cases / (total - cases)

In [21]:
round(kek(11034, 189) / kek(11037, 104), 4)

1.8321

In [6]:
asp = 11037
iasp = 104
plc = 11034
iplc = 189

In [8]:
import numpy as np

In [11]:
def get_bootstrap_samples(data, n_samples):
    indices = np.random.randint(0, len(data), (n_samples, len(data)))
    samples = data[indices]
    return samples

def stat_intervals(stat, alpha):
    boundaries = np.percentile(stat, [100 * alpha / 2., 100 * (1 - alpha / 2.)])
    return boundaries

In [13]:
vasp = np.hstack((np.ones((iasp)),np.zeros((asp-iasp))))
vplc = np.hstack((np.ones((iplc)),np.zeros((plc-iplc))))

T=1000
np.random.seed(0)
bs_asp = get_bootstrap_samples(vasp, T)
bs_plc = get_bootstrap_samples(vplc, T)

stat_asp =(bs_asp.mean(axis=1) / (1-bs_asp.mean(axis=1)))
stat_plc =(bs_plc.mean(axis=1) / (1-bs_plc.mean(axis=1)))

intervals = stat_intervals(stat_plc/stat_asp, 0.05)

In [14]:
round(intervals[0], 4)

1.4442

### Практика проверки гипотез

In [30]:
import pandas as pd

In [31]:
data = pd.read_csv('pines.txt', sep='\t')

In [32]:
data

sn     we
0    200.0    8.8
1    199.3   10.0
2    193.6   22.4
3    167.7   35.6
4    183.9   45.4
..     ...    ...
579  169.1  160.0
580  162.5  157.3
581  156.7  155.3
582  154.1  150.8
583   87.7  200.0

[584 rows x 2 columns]

In [34]:
from scipy import stats

In [57]:
bins = stats.binned_statistic_2d(data['sn'], data['we'], np.ones(data.shape[0]), bins=5, statistic='count')

In [60]:
bins[0].mean()

23.36

In [68]:
round(stats.chisquare(bins[0], bins[0].mean(), ddof=0, axis=None).statistic, 2)

150.59